### ISSUE TITLE
changes in Purchase invoice Section

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext_oralcare#163]
Hi Dev Team,

There are some changes suggested by manish sir in the Purchase Invoice, As we observe some mistake as well some improvements are listed below

1. ON The top add GST NO.
2. On the SGST and CGST their is no "%" sign in the print
3. Rounded off is not shown on the print
4. Gross Total and amount in word is not properly set, please check the same
5. There is note like "Created by Accounts Dept" 

Also attaching another print for Tax suggestion, pls check and revert.

For reference files are attached 
![WhatsApp Image 2019-08-06 at 17 21 47](https://user-images.githubusercontent.com/52345483/62539249-69a95b80-b872-11e9-9200-ad3ea8b29a3a.jpeg)
![WhatsApp Image 2019-08-06 at 17 21 48(1)](https://user-images.githubusercontent.com/52345483/62539250-69a95b80-b872-11e9-901c-25f812e90d0b.jpeg)
![WhatsApp Image 2019-08-06 at 17 21 48](https://user-images.githubusercontent.com/52345483/62539252-6a41f200-b872-11e9-8141-85fa06c3dd23.jpeg)

**Comment by palashjhabak** [comment]
- ON The top add GST NO.
 - On the SGST and CGST their is no "%" sign in the print - **We are using the wrong print out. GST Print have to select when printing the Purchase Invoice. Will make that as default**

Rounded off is not shown on the print - **Will make the rounded total as the grand total as SI**
Gross Total and amount in word is not properly set, please check the same - **Rounded**
There is note like "Created by Accounts Dept" - **Account Dept not possible, I can put the person's name who is creating this just like we have done in Receipt and Purchase entries**
