### ISSUE TITLE
Multiple Doctor Revenue Report required

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext_oralcare#185]
#Required report
Required this report from ERP in Manish sir's Account
Multiple Doctor Revenue Report
Please letus connect for this, and this is urgently requested by Manish sir
Reference Image attached
![WhatsApp Image 2020-01-04 at 16 34 44](https://user-images.githubusercontent.com/52345483/71765547-4adfeb80-2f1c-11ea-9418-235b28a0ef81.jpeg)

**Comment by palashjhabak** [comment]
@pradiporalcare Date filters in this report will be just months right and not individual dates? Also if those are months, will it be in the current financial year or overall?
Please let me know this asap.

**Comment by palashjhabak** [comment]
@pradiporalcare Also just to be clear, first column will have the total Sales Amount right? without any deductions. 2nd column has Consumable cost. What about the admin fees and any other deductions? Also are we talking just about procedures or also the consultation fees and Radiology Investigation charges. Please clarify these asap.

Thanks,
Palash
