### ISSUE TITLE
Error in Individual doctor data sheet and multiple doctor data sheet

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext_oralcare#186]
the another error is coming in the report

	Individual doctor data sheet
	Multiple doctor data sheet

please do needful asap
![Screenshot (216)](https://user-images.githubusercontent.com/52345483/71765555-65b26000-2f1c-11ea-815a-2b5ff0331fd3.png)

**Comment by surajTechlift** [comment]
individual is sorted
