### ISSUE TITLE
Purchase Invoice Printing Changes #URGENT

### ISSUE THREAD

**Issue by contactoralcare** [techlift-tech/erpnext_oralcare#198]
I have attached the ref. Image where all the changes need to be done.
1. Pls adjust date column to fit in the area of single line.
2. On the TOP RHS, pls Add the DATE RANGE
3. The **"Party Account Currency"** is compulsory field, pls remove the option in printing reports.

Thank you!
[img20200217_12541756.pdf](https://github.com/techlift-tech/erpnext_oralcare/files/4212339/img20200217_12541756.pdf)

**Comment by palashjhabak** [comment]
When we create reports on the fly using Report Builder and add certain columns, system automatically adds certain dependent columns ( mostly in case of currency ) which we can remove like in the screenshot below. 

![image](https://user-images.githubusercontent.com/4964924/74633828-8ced8580-5188-11ea-9777-8ec2132e4e52.png)

![image](https://user-images.githubusercontent.com/4964924/74633841-9545c080-5188-11ea-9726-991973a97a02.png)

**Comment by palashjhabak** [comment]
As also mentioned in email, documenting it here also. Changes in print formats is not possible for on the fly reports. When there are more number of columns, please try to print those reports in landscape mode so that more columns can be easily accommodated.

**Comment by palashjhabak** [comment]
@contactoralcare Date range filter is not possible on the top in on the fly reports. I can however add the Date as a filter. Please let me know. Closing this for now, reopen it if you want me to add just the date filter.
